language: php
sudo: false

php:
    - "7.0"
    - "7.1"
    - "7.2"
    - "7.3"

matrix:
    fast_finish: true

install:
    - composer self-update
    - composer update

script:
    - vendor/bin/phpunit
